### ISSUE TITLE
Having trouble figuring out how to disable the highlighting features on mobile browser

### ISSUE THREAD

**Issue by andrewandrepowell** [kniEngine/kni#2217]
The player must repeatedly tap the screen in my current game, but doing so activates the highlighting feature over the whole game window and opens up the copy menu. This happens for both Safari and Chrome.

I've tried creating the following CSS file...

```css
.prevent-select {
    user-select: none; /* supported by Chrome and Opera */
    -webkit-user-select: none; /* Safari */
    -khtml-user-select: none; /* Konqueror HTML */
    -moz-user-select: none; /* Firefox */
    -ms-user-select: none; /* Internet Explorer/Edge */
}
```

...and adding a reference to it in the index.html body like so.

```html
<body>
    <link href="css/utility.css" rel="stylesheet" />
    <div id="app">
        <div id="loading" style="display: table-cell; margin: auto; width:100vw; height:100vh; vertical-align: middle; background: #ffcc10;">
            <div style="display: block; margin: auto; width: 9em; color: white;font-family: 'Segoe UI', sans-serif;">
                <div style="text-align: center; font-size: 0.85em;">Made with<br /><a href="https://github.com/kniEngine/kni"><img src="kni.png" border="0" alt="Kni"></a></div>
                <div style="text-align: center; font-size: 1.8em;">loading&nbsp;<marquee style="width:0.9em; vertical-align: bottom;">.&nbsp;.&nbsp;.&nbsp;&nbsp;&nbsp;</marquee></div>
            </div>
        </div>
    </div>
    ...
```

It would also be nice to see this solution permanently in the KNI BlazorGL template since I can't imagine any reason why anyone would want the highlighting feature enabled by default. 

Still on v3.14.9001, by the way. Haven't switched to 4.0.9001.1 yet.

Thanks in advance!
